// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import tailwind from "@astrojs/tailwind";

// https://astro.build/config
export default defineConfig({
  output: "static",
  integrations: [
    starlight({
      prerender: true,

      // Site metadata
      title: "GNOSIS",

      // Visual settings
      logo: {
        src: "./src/img/favicon.png",
      },
      favicon: "/img/favicon.png",
      customCss: [
        "@fontsource/lato/400.css",
        "@fontsource/lato/700.css",
        "./src/styles/css/tailwind.css",
        "./src/styles/css/base.css",
        "./src/styles/css/custom.css",
      ],
      // i18n
      defaultLocale: "root",
      locales: {
        af: {
          label: "🇿🇦 AF - Afrikaans",
        },
        am: {
          label: "🇪🇹 AM - Amharic",
        },
        ar: {
          dir: "rtl",
          label: "🇸🇦 AR - العربية",
        },
        as: {
          label: "🇮🇳 AS - Assamese",
        },
        az: {
          label: "🇦🇿 AZ - Azerbaijani",
        },
        be: {
          label: "🇧🇾 BE - Belarusian",
        },
        bg: {
          label: "🇧🇬 BG - Bulgarian",
        },
        bm: {
          label: "🇲🇱 BM - Bambara",
        },
        bn: {
          label: "🇧🇩 BN - Bengali",
        },
        bo: {
          label: "🇨🇳 BO - Tibetan",
        },
        br: {
          label: "🇫🇷 BR - Breton",
        },
        brx: {
          label: "🇮🇳 BRX - Bodo",
        },
        bs: {
          label: "🇧🇦 BS - Bosnian",
        },
        ca: {
          label: "🇪🇸 CA - Català",
        },
        cgg: {
          label: "🇺🇬 CGG - Chiga",
        },
        cs: {
          label: "🇨🇿 CS - Čeština",
        },
        cy: {
          label: "🇬🇧 CY - Welsh",
        },
        da: {
          label: "🇩🇰 DA - Dansk",
        },
        de: {
          label: "🇩🇪 DE - Deutsch",
        },
        dje: {
          label: "🇳🇪 DJE - Zarma",
        },
        dv: {
          dir: "rtl",
          label: "🇲🇻 DV - Dhivehi",
        },
        el: {
          label: "🇬🇷 EL - Ελληνικά",
        },
        en: {
          label: "🇬🇧 EN - English",
        },
        eo: {
          label: "🌍 EO - Esperanto",
        },
        root: {
          label: "🇪🇸 ES - Español",
          lang: "es",
        },
        et: {
          label: "🇪🇪 ET - Estonian",
        },
        eu: {
          label: "🇪🇺 EU - Basque",
        },
        fa: {
          dir: "rtl",
          label: "🇮🇷 FA - فارسی",
        },
        ff: {
          label: "🇸🇳 FF - Fulah",
        },
        fil: {
          label: "🇵🇭 FIL - Filipino",
        },
        fi: {
          label: "🇫🇮 FI - Finnish",
        },
        fr: {
          label: "🇫🇷 FR - Français",
        },
        ga: {
          label: "🇮🇪 GA - Irish",
        },
        gu: {
          label: "🇮🇳 GU - Gujarati",
        },
        ha: {
          label: "🇳🇬 HA - Hausa",
        },
        he: {
          dir: "rtl",
          label: "🇮🇱 HE - עברית",
        },
        hi: {
          label: "🇮🇳 HI - हिन्दी",
        },
        hr: {
          label: "🇭🇷 HR - Croatian",
        },
        hu: {
          label: "🇭🇺 HU - Hungarian",
        },
        hy: {
          label: "🇦🇲 HY - Armenian",
        },
        id: {
          label: "🇮🇩 ID - Indonesia",
        },
        ig: {
          label: "🇳🇬 IG - Igbo",
        },
        is: {
          label: "🇮🇸 IS - Icelandic",
        },
        it: {
          label: "🇮🇹 IT - Italiano",
        },
        ja: {
          label: "🇯🇵 JA - 日本語",
        },
        kab: {
          label: "🇩🇿 KAB - Kabyle",
        },
        kam: {
          label: "🇰🇪 KAM - Kamba",
        },
        ka: {
          label: "🇬🇪 KA - Georgian",
        },
        kea: {
          label: "🇨🇻 KEA - Kabuverdianu",
        },
        kk: {
          label: "🇰🇿 KK - Kazakh",
        },
        kln: {
          label: "🇰🇪 KLN - Kalenjin",
        },
        km: {
          label: "🇰🇭 KM - Khmer",
        },
        kmr: {
          dir: "rtl",
          label: "🇹🇷 KMR - Northern Kurdish",
        },
        kn: {
          label: "🇮🇳 KN - Kannada",
        },
        ko: {
          label: "🇰🇷 KO - 한국어",
        },
        kok: {
          label: "🇮🇳 KOK - Konkani",
        },
        ky: {
          label: "🇰🇬 KY - Kyrgyz",
        },
        lag: {
          label: "🇹🇿 LAG - Langi",
        },
        lao: {
          label: "🇱🇦 LAO - Laotian",
        },
        lg: {
          label: "🇺🇬 LG - Ganda",
        },
        ln: {
          label: "🇨🇩 LN - Lingala",
        },
        lt: {
          label: "🇱🇹 LT - Lithuanian",
        },
        lv: {
          label: "🇱🇻 LV - Latvian",
        },
        mk: {
          label: "🇲🇰 MK - Macedonian",
        },
        mg: {
          label: "🇲🇬 MG - Malagasy",
        },
        mer: {
          label: "🇰🇪 MER - Meru",
        },
        ml: {
          label: "🇮🇳 ML - Malayalam",
        },
        mn: {
          label: "🇲🇳 MN - Mongolian",
        },
        mr: {
          label: "🇮🇳 MR - Marathi",
        },
        ms: {
          label: "🇲🇾 MS - Malay",
        },
        mt: {
          label: "🇲🇹 MT - Maltese",
        },
        my: {
          label: "🇲🇲 MY - Burmese",
        },
        nb: {
          label: "🇳🇴 NB - Norsk Bokmål",
        },
        ne: {
          label: "🇳🇵 NE - Nepali",
        },
        nl: {
          label: "🇳🇱 NL - Nederlands",
        },
        nus: {
          label: "🇸🇸 NUS - Nuer",
        },
        om: {
          label: "🇪🇹 OM - Oromo",
        },
        or: {
          label: "🇮🇳 OR - Oriya",
        },
        pa: {
          label: "🇮🇳 PA - Punjabi",
        },
        pl: {
          label: "🇵🇱 PL - Polski",
        },
        ps: {
          dir: "rtl",
          label: "🇦🇫 PS - Pashto",
        },
        pt: {
          label: "🇵🇹 PT - Português",
        },
        "pt-br": {
          label: "🇧🇷 PT-BR - Português do Brasil",
          lang: "pt-br",
        },
        ro: {
          label: "🇷🇴 RO - Română",
        },
        ru: {
          label: "🇷🇺 RU - Русский",
        },
        rw: {
          label: "🇷🇼 RW - Kinyarwanda",
        },
        sg: {
          label: "🇨🇫 SG - Sango",
        },
        si: {
          label: "🇱🇰 SI - Sinhala",
        },
        sk: {
          label: "🇸🇰 SK - Slovenčina",
        },
        sl: {
          label: "🇸🇮 SL - Slovenian",
        },
        sn: {
          label: "🇿🇼 SN - Shona",
        },
        so: {
          label: "🇸🇴 SO - Somali",
        },
        sq: {
          label: "🇦🇱 SQ - Albanian",
        },
        sr: {
          label: "🇷🇸 SR - Serbian",
        },
        sv: {
          label: "🇸🇪 SV - Svenska",
        },
        sw: {
          label: "🇹🇿 SW - Swahili",
        },
        swc: {
          label: "🇨🇩 SWC - Congo Swahili",
        },
        ta: {
          label: "🇮🇳 TA - Tamil",
        },
        te: {
          label: "🇮🇳 TE - Telugu",
        },
        th: {
          label: "🇹🇭 TH - Thai",
        },
        ti: {
          label: "🇪🇷 TI - Tigrinya",
        },
        tk: {
          label: "🇹🇲 TK - Turkmen",
        },
        tr: {
          label: "🇹🇷 TR - Türkçe",
        },
        uk: {
          label: "🇺🇦 UK - Українська",
        },
        ur: {
          dir: "rtl",
          label: "🇵🇰 UR - Urdu",
        },
        uz: {
          label: "🇺🇿 UZ - Uzbek",
        },
        vi: {
          label: "🇻🇳 VI - Tiếng Việt",
        },
        yo: {
          label: "🇳🇬 YO - Yoruba",
        },
        zh: {
          label: "🇨🇳 ZH - 中文",
        },
        zu: {
          label: "🇿🇦 ZU - Zulu",
        },
      },

      // Components
      components: {
        Footer: "./src/components/override/Footer.astro",
        Header: "./src/components/override/Header.astro",
        Sidebar: "./src/components/override/Sidebar.astro",
        TableOfContents: "./src/components/override/TableOfContents.astro",
      },

      // Social links
      social: {},

      // Sidebar links
      sidebar: [
        {
          label: "Libros",
          slug: "",
          translations: {
            af: "Boeke",
            am: "መጽሐፍት",
            ar: "كتب",
            as: "কিতাপ",
            az: "Kitablar",
            be: "Кнігі",
            bg: "Книги",
            bm: "Gafew",
            bn: "বই",
            bo: "དཔེ་ཆ།",
            br: "Levrioù",
            brx: "बिजाब",
            bs: "Knjige",
            ca: "Llibres",
            cgg: "Ebitabo",
            cs: "Knihy",
            cy: "Llyfrau",
            da: "Bøger",
            de: "Bücher",
            dje: "Citaabey",
            dv: "ފޮތްތައް",
            el: "Βιβλία",
            en: "Books",
            eo: "Libroj",
            root: "Libros",
            et: "Raamatud",
            eu: "Liburuak",
            fa: "کتاب‌ها",
            ff: "Deftere",
            fil: "Mga Libro",
            fi: "Kirjat",
            fr: "Livres",
            ga: "Leabhair",
            gu: "પુસ્તકો",
            ha: "Littattafai",
            he: "ספרים",
            hi: "पुस्तकें",
            hr: "Knjige",
            hu: "Könyvek",
            hy: "Գրքեր",
            id: "Buku",
            ig: "Akwụkwọ",
            is: "Bækur",
            it: "Libri",
            ja: "本",
            kab: "Idlisen",
            kam: "Mawuku",
            ka: "წიგნები",
            kea: "Livrus",
            kk: "Кітаптар",
            kln: "Buget",
            km: "សៀវភៅ",
            kmr: "Pirtûk",
            kn: "ಪುಸ್ತಕಗಳು",
            ko: "책",
            kok: "पुस्तकां",
            ky: "Китептер",
            lag: "Vitabu",
            lao: "ປື້ມ",
            lg: "Ebitabo",
            ln: "Babúku",
            lt: "Knygos",
            lv: "Grāmatas",
            mk: "Книги",
            mg: "Boky",
            mer: "Mabuku",
            ml: "പുസ്തകങ്ങൾ",
            mn: "Ном",
            mr: "पुस्तके",
            ms: "Buku",
            mt: "Kotba",
            my: "စာအုပ်များ",
            nb: "Bøker",
            ne: "पुस्तकहरू",
            nl: "Boeken",
            nus: "Kitaap",
            om: "Kitaabota",
            or: "ବହି",
            pa: "ਕਿਤਾਬਾਂ",
            pl: "Książki",
            ps: "کتابونه",
            pt: "Livros",
            "pt-br": "Livros",
            ro: "Cărți",
            ru: "Книги",
            rw: "Ibitabo",
            sg: "Mbeti",
            si: "පොත්",
            sk: "Knihy",
            sl: "Knjige",
            sn: "Mabhuku",
            so: "Buugaag",
            sq: "Libra",
            sr: "Књиге",
            sv: "Böcker",
            sw: "Vitabu",
            swc: "Vitabu",
            ta: "புத்தகங்கள்",
            te: "పుస్తకాలు",
            th: "หนังสือ",
            ti: "መጽሓፍቲ",
            tk: "Kitaplar",
            tr: "Kitaplar",
            uk: "Книги",
            ur: "کتابیں",
            uz: "Kitoblar",
            vi: "Sách",
            yo: "Àwọn Ìwé",
            zh: "书",
            zu: "Izincwadi",
          },
        },
        {
          label: "Educación Fundamental",
          collapsed: true,
          translations: {
            af: "Fundamentele Onderwys",
            am: "መሰረታዊ ትምህርት",
            ar: "التعليم الأساسي",
            as: "মৌলিক শিক্ষা",
            az: "Əsas Təhsil",
            be: "Фундаментальная Адукацыя",
            bg: "Основно Образование",
            bm: "Kalan Sabatili",
            bn: "মৌলিক শিক্ষা",
            bo: "གཞི་རྩའི་ཤེས་ཡོན།",
            br: "Deskadurezh Diazez",
            brx: "मौलिक सोलोंथाय",
            bs: "Osnovno Obrazovanje",
            ca: "Educació Bàsica",
            cgg: "Okwega Okukuru",
            cs: "Základní Vzdělávání",
            cy: "Addysg Sylfaenol",
            da: "Fundamental Uddannelse",
            de: "Grundbildung",
            dje: "Cawyan Aasaasiya",
            dv: "އަސާސީ ތަޢުލީމު",
            el: "Βασική Εκπαίδευση",
            en: "Fundamental Education",
            eo: "Fundamenta Edukado",
            root: "Educación Fundamental",
            et: "Põhiharidus",
            eu: "Oinarrizko Hezkuntza",
            fa: "آموزش ابتدایی",
            ff: "Jannginde Asasi",
            fil: "Pangunahing Edukasyon",
            fi: "Perusopetus",
            fr: "Éducation Fondamentale",
            ga: "Oideachas Bunúsach",
            gu: "મૂળભૂત શિક્ષણ",
            ha: "Ilimi Na Asali",
            he: "חינוך בסיסי",
            hi: "मौलिक शिक्षा",
            hr: "Osnovno Obrazovanje",
            hu: "Alapvető Oktatás",
            hy: "Հիմնական Կրթություն",
            id: "Pendidikan Dasar",
            ig: "Mmụta Ntọala",
            is: "Grunnskólamenntun",
            it: "Educazione Fondamentale",
            ja: "基礎教育",
            kab: "Aselmed Azadur",
            kam: "Masomo ma Nzeo",
            ka: "ძირითადი განათლება",
            kea: "Idukason Fundamental",
            kk: "Негізгі Білім",
            kln: "Kenyisiet Ne Mining",
            km: "ការអប់រំមូលដ្ឋាន",
            kmr: "Perwerdehiya Bingehîn",
            kn: "ಮೂಲಭೂತ ಶಿಕ್ಷಣ",
            ko: "기본 교육",
            kok: "मूलभूत शिक्षण",
            ky: "Негизги Билим Берүү",
            lag: "Elimu ya Msingi",
            lao: "ການສຶກສາຂັ້ນພື້ນຖານ",
            lg: "Okusoma Okusookerwako",
            ln: "Kelási ya Libosó",
            lt: "Pagrindinis Išsilavinimas",
            lv: "Pamata Izglītība",
            mk: "Основно Образование",
            mg: "Fanabeazana Fototra",
            mer: "Githomo kia Nthiguru",
            ml: "അടിസ്ഥാന വിദ്യാഭ്യാസം",
            mn: "Суурь Боловсрол",
            mr: "मूलभूत शिक्षण",
            ms: "Pendidikan Asas",
            mt: "Edukazzjoni Fundamentali",
            my: "အခြေခံပညာရေး",
            nb: "Grunnleggende Utdanning",
            ne: "आधारभूत शिक्षा",
            nl: "Fundamenteel Onderwijs",
            nus: "Piöcku Duëëth",
            om: "Barnoota Bu'uuraa",
            or: "ମୌଳିକ ଶିକ୍ଷା",
            pa: "ਮੁੱਢਲੀ ਸਿੱਖਿਆ",
            pl: "Edukacja Podstawowa",
            ps: "بنسټیز زده کړې",
            pt: "Educação Fundamental",
            "pt-br": "Educação Fundamental",
            ro: "Educație Fundamentală",
            ru: "Основное образование",
            rw: "Uburezi bw'Ibanze",
            sg: "Fängö tî Nzapa",
            si: "මූලික අධ්‍යාපනය",
            sk: "Základné Vzdelávanie",
            sl: "Osnovno Izobraževanje",
            sn: "Dzidzo Yepasi",
            so: "Waxbarashada Aasaasiga",
            sq: "Arsimi Themelor",
            sr: "Основно Образовање",
            sv: "Grundutbildning",
            sw: "Elimu ya Msingi",
            swc: "Elimu ya Msingi",
            ta: "அடிப்படை கல்வி",
            te: "ప్రాథమిక విద్య",
            th: "การศึกษาขั้นพื้นฐาน",
            ti: "መሰረታዊ ትምህርቲ",
            tk: "Esasy Bilim",
            tr: "Temel Eğitim",
            uk: "Фундаментальна Освіта",
            ur: "بنیادی تعلیم",
            uz: "Asosiy Ta'lim",
            vi: "Giáo Dục Cơ Bản",
            yo: "Ẹ̀kọ́ Ìpìlẹ̀",
            zh: "基础教育",
            zu: "Imfundo Eyisisekelo",
          },
          autogenerate: { directory: "educacion-fundamental", collapsed: true },
        },
        {
          label: "Tratado de Psicología Revolucionaria",
          collapsed: true,
          translations: {
            af: "Verhandeling oor Revolusionêre Sielkunde",
            am: "የአብዮታዊ ስነ-ልቦና መጽሐፍ",
            ar: "معاهدة علم النفس الثوري",
            as: "বিপ্লৱী মনোবিজ্ঞানৰ গ্ৰন্থ",
            az: "İnqilabi Psixologiya Haqqında Traktat",
            be: "Трактат па Рэвалюцыйнай Псіхалогіі",
            bg: "Трактат за Революционна Психология",
            bm: "Hadamaden Yɛlɛma Dɔnniya Sɛbɛn",
            bn: "বিপ্লবী মনোবিজ্ঞানের গ্রন্থ",
            bo: "གསར་བརྗེའི་སེམས་ཁམས་རིག་པའི་གཞུང་།",
            br: "Traetiz war Psikologiezh Dispac'hel",
            brx: "बिप्लाबारि मोनोबिज्ञान बिजाब",
            bs: "Traktat o Revolucionarnoj Psihologiji",
            ca: "Tractat de Psicologia Revolucionària",
            cgg: "Ekitabo ky'Okwetegyereza Emitwarize y'Abantu",
            cs: "Pojednání o Revoluční Psychologii",
            cy: "Traethawd ar Seicoleg Chwyldroadol",
            da: "Afhandling om Revolutionær Psykologi",
            de: "Abhandlung über Revolutionäre Psychologie",
            dje: "Lakkal Barmay Bayrey Tiira",
            dv: "އިންޤިލާބީ ނަފްސާނީ ޢިލްމުގެ މުޢާހަދާ",
            el: "Πραγματεία Επαναστατικής Ψυχολογίας",
            en: "Treatise on Revolutionary Psychology",
            eo: "Traktato pri Revolucia Psikologio",
            root: "Tratado de Psicología Revolucionaria",
            et: "Traktaat Revolutsioonilisest Psühholoogiast",
            eu: "Psikologia Iraultzaileari Buruzko Tratatua",
            fa: "رساله روانشناسی انقلابی",
            ff: "Winnditagol Dow Anndal Hakkillo Waylitaago",
            fil: "Kasulatan sa Rebolusyonaryong Sikolohiya",
            fi: "Tutkielma Vallankumouksellisesta Psykologiasta",
            fr: "Traité de Psychologie Révolutionnaire",
            ga: "Tráchtas ar Shíceolaíocht Réabhlóideach",
            gu: "ક્રાંતિકારી મનોવિજ્ઞાન પર ગ્રંથ",
            ha: "Littafi akan Ilimin Hankali na Juyin Juya",
            he: "מסכת פסיכולוגיה מהפכנית",
            hi: "क्रांतिकारी मनोविज्ञान का ग्रंथ",
            hr: "Rasprava o Revolucionarnoj Psihologiji",
            hu: "Értekezés a Forradalmi Pszichológiáról",
            hy: "Տրակտատ Հեղափոխական Հոգեբանության Մասին",
            id: "Risalah Psikologi Revolusioner",
            ig: "Akwụkwọ Gbasara Sayịkọlọjị Agha Mgbanwe",
            is: "Ritgerð um Byltingarkennda Sálfræði",
            it: "Trattato di Psicologia Rivoluzionaria",
            ja: "革命的心理学論",
            kab: "Adlis ɣef Tasnefsant Taɣerfant",
            kam: "Mundu wa Kisayikoloji kya Nzeo",
            ka: "ტრაქტატი რევოლუციურ ფსიქოლოგიაზე",
            kea: "Tratadu di Psikolojia Revolusionáriu",
            kk: "Революциялық Психология Туралы Трактат",
            kln: "Kitabu ap Saikoloji ne Lelutiet",
            km: "គម្ពីរស្តីពីចិត្តវិទ្យាបដិវត្តន៍",
            kmr: "Vekolîna li ser Psîkolojiya Şoreşgerî",
            kn: "ಕ್ರಾಂತಿಕಾರಿ ಮನೋವಿಜ್ಞಾನದ ಗ್ರಂಥ",
            ko: "혁명적 심리학 논문",
            kok: "क्रांतिकारी मानसशास्त्राचो ग्रंथ",
            ky: "Революциялык Психология Боюнча Трактат",
            lag: "Kitabu cha Saikolojia ya Mapinduzi",
            lao: "ບົດຄວາມກ່ຽວກັບຈິດຕະວິທະຍາປະຕິວັດ",
            lg: "Ekitabo ky'Okwetegereza Embeera y'Abantu",
            ln: "Mokanda ya Boyebi bwa Makanisi ya Revolisyo",
            lt: "Traktatas apie Revoliucinę Psichologiją",
            lv: "Traktāts par Revolucionāro Psiholoģiju",
            mk: "Трактат за Револуционерна Психологија",
            mg: "Boky momba ny Siansa Saina Revolisionera",
            mer: "Kibuku kia Saikologia ya Mageukanio",
            ml: "വിപ്ലവകരമായ മനഃശാസ്ത്രത്തെക്കുറിച്ചുള്ള പ്രബന്ധം",
            mn: "Хувьсгалт Сэтгэл Судлалын Тухай Зохиол",
            mr: "क्रांतिकारी मानसशास्त्रावरील ग्रंथ",
            ms: "Risalah Psikologi Revolusioner",
            mt: "Trattat dwar Psikoloġija Rivoluzzjonarja",
            my: "တော်လှန်ရေးစိတ်ပညာဆိုင်ရာကျမ်း",
            nb: "Avhandling om Revolusjonær Psykologi",
            ne: "क्रान्तिकारी मनोविज्ञान सम्बन्धी ग्रन्थ",
            nl: "Verhandeling over Revolutionaire Psychologie",
            nus: "Kitap në Gël Nhialic",
            om: "Barreeffama Xiinxala Sammuu革命的",
            or: "ବିପ୍ଳବାତ୍ମକ ମନୋବିଜ୍ଞାନ ଉପରେ ଗ୍ରନ୍ଥ",
            pa: "ਇਨਕਲਾਬੀ ਮਨੋਵਿਗਿਆਨ ਦਾ ਗ੍ਰੰਥ",
            pl: "Traktat o Psychologii Rewolucyjnej",
            ps: "د انقلابي ارواپوهنې په اړه رساله",
            pt: "Tratado de Psicologia Revolucionária",
            "pt-br": "Tratado de Psicologia Revolucionária",
            ro: "Tratat de Psihologie Revoluționară",
            ru: "Трактат о Революционной Психологии",
            rw: "Igitabo cy'Ubuhanga bw'Imyifatire y'Impinduramatwara",
            sg: "Mbeti tî Mayê tî Bata-ndo tî Revolution",
            si: "විප්ලවීය මනෝ විද්‍යාව පිළිබඳ ග්‍රන්ථය",
            sk: "Pojednanie o Revolučnej Psychológii",
            sl: "Razprava o Revolucionarni Psihologiji",
            sn: "Bhuku reZvidzidzo zvePfungwa dzeRuvolution",
            so: "Buugga Cilmi-nafsiga Kacaanka",
            sq: "Traktat mbi Psikologjinë Revolucionare",
            sr: "Трактат о Револуционарној Психологији",
            sv: "Avhandling om Revolutionär Psykologi",
            sw: "Kitabu cha Saikolojia ya Mapinduzi",
            swc: "Kitabu cha Saikolojia ya Mapinduzi",
            ta: "புரட்சிகர உளவியல் பற்றிய ஆய்வு நூல்",
            te: "విప్లవాత్మక మనస్తత్వ శాస్త్రం పై గ్రంథం",
            th: "ตำราจิตวิทยาปฏิวัติ",
            ti: "መጽሓፍ ብዛዕባ ሰውራዊ ስነ-ልቦና",
            tk: "Rewolýusion Psihologiýasy Barada Traktat",
            tr: "Devrimci Psikoloji Üzerine İnceleme",
            uk: "Трактат про Революційну Психологію",
            ur: "انقلابی نفسیات پر مقالہ",
            uz: "Inqilobiy Psixologiya Haqida Risola",
            vi: "Luận Văn về Tâm Lý Học Cách Mạng",
            yo: "Ìwé nípa Ìmọ̀ Ọkàn Ajẹ́míyọ̀rọ̀",
            zh: "革命心理学论",
            zu: "Incwadi Yesifundo Sengqondo Yezinguquko",
          },
          autogenerate: {
            directory: "tratado-de-psicologia-revolucionaria",
            collapsed: true,
          },
        },
      ],
    }),
    tailwind(),
  ],
});
